language: python
dist: trusty
group: edge
before_install:
  # In normal circunstances we would just do "pip install wxPython"
  - pip install https://wxpython.org/Phoenix/snapshot-builds/linux/gtk3/ubuntu-14.04/wxPython-4.0.0a3.dev3059+4a5c5d9-cp27-cp27mu-linux_x86_64.whl
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
matrix:
  include:
    - python: "2.7"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - invoke test
