language: python
dist: trusty
group: edge
before_install:
  - pip install wxPython
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
matrix:
  include:
    - python: "2.7"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - pip install robotframework
script:
  - invoke test
